"""adicionar constraint única de código de unidade por organização

Revision ID: c2343765cb81
Revises: a1788843e317
Create Date: 2026-08-19 14:19:29.707930
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c2343765cb81'
down_revision: str | None = 'a1788843e317'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_organizational_units_org_code', 'organizational_units', ['organization_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_organizational_units_org_code', 'organizational_units', type_='unique')
    # ### end Alembic commands ###